export const POSITION_BASE_QUESTION_COUNT = 30;
export const POSITION_RECOMMENDED_MIN_COUNT = 20;
export const POSITION_RECOMMENDED_MAX_COUNT = 30;
export const POSITION_TOTAL_QUESTION_COUNT =
  POSITION_BASE_QUESTION_COUNT + POSITION_RECOMMENDED_MAX_COUNT;
